language: node_js
cache:
  directories
    - node_modules
    - ~/.npm
node_js:
    - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
    email:
        recipients:
            - leomed2005@gmail.com
            - leomed2002@hotmail.com
          on_success: allways
          on_failure: allways
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: master
  